apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-navigator
  namespace: ai-navigator
  labels:
    app.kubernetes.io/part-of: ai-navigator
    app.kubernetes.io/component: operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-navigator-operator
  namespace: ai-navigator
  labels:
    app.kubernetes.io/part-of: ai-navigator
    app.kubernetes.io/component: operator
