apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-navigator

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - hpa.yaml
  - pdb.yaml

commonLabels:
  app.kubernetes.io/name: ai-navigator
  app.kubernetes.io/version: "0.1.0"
  app.kubernetes.io/managed-by: kustomize

images:
  - name: quay.io/opendatahub/ai-navigator
    newTag: latest
