apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ai-navigator
  namespace: ai-navigator
  labels:
    app.kubernetes.io/name: ai-navigator
  annotations:
    haproxy.router.openshift.io/timeout: 5m
spec:
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: ai-navigator
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
